import { getCloneableObject, safeStringify } from "ap-shared-core/out/objectUtil.js";
import fs from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import { IPC_API_KEY, IPC_GET_KEY, UC_ACCESS_KEY } from "../../common/ipc/enumAndMore.js";
import { AssemblyManager } from "../../renderer/Assembly.js";
import { ResourceStorage } from "../ResourceStorage.js";
export function IpcMainGroup(regKey) {
    if (typeof window !== "undefined")
        return;
    //PathBridge.path = path as any;
    //PathBridge.url = url as any;
    let urlObj = regKey; // GetRootPathByUrl_M(urlpath, configManage.filler.ucConfigList);
    let rtrn = {
        On: (key, callback) => {
            return IpcMainHelper.On(key, callback, urlObj);
        },
        Handle: (key, callback) => {
            return IpcMainHelper.Handle(key, callback, urlObj);
        },
        Send: (key, evt, ...args) => {
            IpcMainHelper.Send(key, evt, args, urlObj);
            //evt.sender.send(key, callback, urlPath);
        },
        Reply: (key, evt, ...args) => {
            IpcMainHelper.Reply(key, evt, args /*[...args]*/, urlObj);
            //evt.sender.send(key, callback, urlPath);
        }
    };
    return rtrn;
}
export class IpcMainHelper {
    static Send(actionKey, evt, args, importMetaUrl = "") {
        args = getCloneableObject(args);
        //args.forEach(s => s = getCloneableObject(s));
        evt.sender.send(IPC_API_KEY, IPC_GET_KEY(actionKey, importMetaUrl), ...args);
    }
    static Reply(actionKey, evt, args, importMetaUrl = "") {
        //console.log(...args);
        args = getCloneableObject(args);
        //args.forEach(s => s = getCloneableObject(s));
        evt.reply(IPC_API_KEY, IPC_GET_KEY(actionKey, importMetaUrl), ...args);
    }
    static IPC_ON = new Map(); //{ [actionKey: string]: IpcMainCallBack } = {};
    static IPC_HANDLE = new Map(); // { [actionKey: string]: IpcMainInvokeCallBack } = {};
    static On(actionKey, callback, importMetaUrl = "") {
        actionKey = IPC_GET_KEY(actionKey, importMetaUrl);
        //console.log(actionKey+' trying to register');
        if (!this.IPC_ON.has(actionKey))
            this.IPC_ON.set(actionKey, callback);
    }
    static Handle(actionKey, callback, importMetaUrl = "") {
        actionKey = IPC_GET_KEY(actionKey, importMetaUrl);
        if (!this.IPC_HANDLE.has(actionKey))
            this.IPC_HANDLE.set(actionKey, callback);
    }
    /**
     * @param resourceFile a resourcefile generated by designer file builder (Resources.ts)
     */
    static async init(resourceFile) {
        await resourceFile;
        const { ipcMain } = await import("electron");
        ipcMain.on(IPC_API_KEY, (event, ...args) => {
            let actionKey = args.shift();
            if (this.IPC_ON.has(actionKey))
                this.IPC_ON.get(actionKey)(event, ...args);
            else {
                //configManage.filler.savePreLoadFilePath(actionKey);
                console.log(`!!! no 'ON EVENT' found [${actionKey}]`);
            }
        });
        ipcMain.handle(IPC_API_KEY, async (event, ...args) => {
            let actionKey = args.shift();
            if (this.IPC_HANDLE.has(actionKey))
                return await this.IPC_HANDLE.get(actionKey)(event, ...args);
            else {
                console.log(`no 'HANDLE EVENT' found [${actionKey}]`);
                return undefined;
            }
        });
        (await import('../ResourceManage.ipc.js')).default();
        IpcMainHelper.On('assemblies', (event, args) => {
            event.returnValue = AssemblyManager.getAssemblies();
        }, UC_ACCESS_KEY);
    }
    static INITIAL_SCRIPT = "";
    static async loadURL(_path, win, options) {
        console.log('configManage inited.');
        let htmlUrl, htmlPath;
        if (_path.startsWith('file:///')) {
            htmlUrl = _path;
            htmlPath = fileURLToPath(_path);
        }
        else {
            htmlUrl = pathToFileURL(_path).href;
            htmlPath = _path;
        }
        const baseURLForDataURL = options?.baseURLForDataURL ?? htmlUrl;
        let html = fs.readFileSync(htmlPath, "utf-8");
        //  let projectDirList = await scanAllProjects();
        let importMap = ResourceStorage.RuntimeProps['importmap'];
        importMap = (importMap != undefined) ? importMap : {};
        const importMapScript = `<script type="importmap">${safeStringify(importMap)}</script>`;
        //<script type="module" > await import("ucbuilder/out/InitRenderer.js"); </script>
        //console.log(importMapScript);
        const headRegex = /<head\b[^>]*>/i;
        const htmlRegex = /<html\b[^>]*>/i;
        if (headRegex.test(html)) {
            html = html.replace(headRegex, match => match + importMapScript);
        }
        else if (htmlRegex.test(html)) {
            html = html.replace(htmlRegex, match => `${match}\n<head>${importMapScript}</head>`);
        }
        else {
            html = `${importMapScript}\n${html}`;
        }
        win.loadURL("data:text/html;charset=utf-8," + encodeURIComponent(html), options);
    }
}
//# sourceMappingURL=IpcMainHelper.js.map