import { type BrowserWindow, type IpcMainEvent } from "electron";
import { IPC_REGISTER_KEY } from "../../common/ipc/enumAndMore.js";
type IpcMainCallBack = (e: import("electron").IpcMainEvent, ...args: any[]) => void;
type IpcMainInvokeCallBack = (e: import("electron").IpcMainInvokeEvent, ...args: any[]) => Promise<any>;
interface IGroupMain {
    On: (actionKey: string, callback: IpcMainCallBack) => void;
    Handle: (actionKey: string, callback: IpcMainInvokeCallBack) => void;
    Send: (actionKey: string, evt: IpcMainEvent, ...args: any[]) => void;
    Reply: (actionKey: string, evt: IpcMainEvent, ...args: any[]) => void;
}
export declare function IpcMainGroup(regKey: string): IGroupMain;
export declare class IpcMainHelper {
    static Send(actionKey: string, evt: IpcMainEvent, args: any[], importMetaUrl?: IPC_REGISTER_KEY): void;
    static Reply(actionKey: string, evt: IpcMainEvent, args: any[], importMetaUrl?: IPC_REGISTER_KEY): void;
    static IPC_ON: Map<string, IpcMainCallBack>;
    static IPC_HANDLE: Map<string, IpcMainInvokeCallBack>;
    static On(actionKey: string, callback: IpcMainCallBack, importMetaUrl?: IPC_REGISTER_KEY): void;
    static Handle(actionKey: string, callback: IpcMainInvokeCallBack, importMetaUrl?: IPC_REGISTER_KEY): void;
    /**
     * @param resourceFile a resourcefile generated by designer file builder (Resources.ts)
     */
    static init(resourceFile: Promise<any>): Promise<void>;
    static INITIAL_SCRIPT: string;
    static loadURL(_path: string, win: BrowserWindow, options?: Electron.LoadURLOptions): Promise<void>;
}
export {};
