 
import type  { BrowserWindow, IpcMainEvent } from "electron";
import fs from "node:fs";
import { join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { IPC_GET_KEY, IPC_REGISTER_KEY, UC_ACCESS_KEY } from "../../common/ipc/enumAndMore.js";
import { AssemblyManager } from "../../renderer/Assembly.js";
import { ResourceStorage } from "../ResourceStorage.js";
import { injectImportMap } from "./importMapGenerator.js";
import { getCloneableObject } from "ap-shared-core/core-common.js";
type IpcMainCallBack = (e: import("electron").IpcMainEvent, ...args: any[]) => void;
type IpcMainInvokeCallBack = (e: import("electron").IpcMainInvokeEvent, ...args: any[]) => Promise<any>;

interface IGroupMain {
    On: (actionKey: string, callback: IpcMainCallBack) => void,
    Handle: (actionKey: string, callback: IpcMainInvokeCallBack) => void,
    Send: (actionKey: string, evt: IpcMainEvent, ...args: any[]) => void,
    Reply: (actionKey: string, evt: IpcMainEvent, ...args: any[]) => void,
}

export function IpcMainGroup(regKey: string): IGroupMain {
    if (typeof window !== "undefined") return;
    //PathBridge.path = path as any;
    //PathBridge.url = url as any;

    let urlObj = regKey;// GetRootPathByUrl_M(urlpath, configManage.filler.ucConfigList);
    let rtrn: IGroupMain = {
        On: (key, callback) => {
            return IpcMainHelper.On(key, callback, urlObj);
        },
        Handle: (key, callback) => {
            return IpcMainHelper.Handle(key, callback, urlObj);
        },
        Send: (key, evt: IpcMainEvent, ...args: any[]) => {
            IpcMainHelper.Send(key, evt, args, urlObj);
            //evt.sender.send(key, callback, urlPath);
        },
        Reply: (key, evt: IpcMainEvent, ...args: any[]) => {


            IpcMainHelper.Reply(key, evt, args/*[...args]*/, urlObj);
            //evt.sender.send(key, callback, urlPath);
        }
    };
    return rtrn;
}
export class IpcMainHelper {
    static Send(actionKey: string, evt: IpcMainEvent, args: any[], importMetaUrl: IPC_REGISTER_KEY = "") {
        args = getCloneableObject(args);
        //args.forEach(s => s = getCloneableObject(s));
        evt.sender.send(AssemblyManager.AKey, IPC_GET_KEY(actionKey, importMetaUrl), ...args);
    }
    static Reply(actionKey: string, evt: IpcMainEvent, args: any[], importMetaUrl: IPC_REGISTER_KEY = "") {
        //console.log(...args);

        args = getCloneableObject(args);
        //args.forEach(s => s = getCloneableObject(s));
        evt.reply(AssemblyManager.AKey, IPC_GET_KEY(actionKey, importMetaUrl), ...args);
    }
    static IPC_ON = new Map<string, IpcMainCallBack>(); //{ [actionKey: string]: IpcMainCallBack } = {};
    static IPC_HANDLE = new Map<string, IpcMainInvokeCallBack>(); // { [actionKey: string]: IpcMainInvokeCallBack } = {};
    static On(actionKey: string, callback: IpcMainCallBack, importMetaUrl: IPC_REGISTER_KEY = "") {
        actionKey = IPC_GET_KEY(actionKey, importMetaUrl);
        //console.log(actionKey+' trying to register');

        if (!this.IPC_ON.has(actionKey))
            this.IPC_ON.set(actionKey, callback);
    }
    static Handle(actionKey: string, callback: IpcMainInvokeCallBack, importMetaUrl: IPC_REGISTER_KEY = "") {
        actionKey = IPC_GET_KEY(actionKey, importMetaUrl);
        if (!this.IPC_HANDLE.has(actionKey))
            this.IPC_HANDLE.set(actionKey, callback);
    }
    /**
     * @param resourceFile a resourcefile generated by designer file builder (Resources.ts)
     */
    static async init(/*resourceFile: Promise<any>*/) {
        //await resourceFile;

        console.log(['MAIN', AssemblyManager.AKey]);

        const { ipcMain } = await import("electron");

        ipcMain.on(AssemblyManager.AKey, (event, ...args: any[]) => {
            let actionKey = args.shift();
            if (this.IPC_ON.has(actionKey))
                this.IPC_ON.get(actionKey)(event, ...args);
            else {
                //configManage.filler.savePreLoadFilePath(actionKey);
                console.log(`!!! no 'ON EVENT' found [${actionKey}]`);
            }
        });
        ipcMain.handle(AssemblyManager.AKey, async (event, ...args: any[]) => {
            let actionKey = args.shift();
            if (this.IPC_HANDLE.has(actionKey))
                return await this.IPC_HANDLE.get(actionKey)(event, ...args);
            else {
                console.log(`no 'HANDLE EVENT' found [${actionKey}]`);
                return undefined;
            }
        });

        (await import('../ResourceManage.ipc.js')).default();
        IpcMainHelper.On('aKey', (event, args: {}) => {
            event.returnValue = AssemblyManager.AKey;
        }, UC_ACCESS_KEY);
        IpcMainHelper.On('assemblies', (event, args: {}) => {
            event.returnValue = AssemblyManager.getAssemblies();
        }, UC_ACCESS_KEY);
    }
    static INITIAL_SCRIPT = "";

    static async load(win: BrowserWindow, options?: Electron.LoadURLOptions, codeFilePath?: string) {
        let htmlContent = ResourceStorage.RuntimeProps['htmlcontent'];
        if (htmlContent == undefined) {
            //const cfile = codeFilePath.
            htmlContent = `<!DOCTYPE html>
<html> 
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="content-type" content="application/xhtml+xml; charset=utf-8" />  
  <script type="module" src="${codeFilePath}"></script>
</head> 
<body>
</body> 
</html>`;
        }
        console.log('configManage inited.');
        htmlContent = injectImportMap(htmlContent, ResourceStorage.RuntimeProps['importmap']);
        await this._load("data:text/html;charset=utf-8," + encodeURIComponent(htmlContent), win, options);
    }
    static async loadContent(htmlContent: string, win: BrowserWindow, options?: Electron.LoadURLOptions) {
        console.log('configManage inited.');
        htmlContent = injectImportMap(htmlContent, ResourceStorage.RuntimeProps['importmap']);
        await this._load("data:text/html;charset=utf-8," + encodeURIComponent(htmlContent), win, options);
    }
    static async loadURL(_path: string, win: BrowserWindow, options?: Electron.LoadURLOptions) {
        console.log('configManage inited.');
        let htmlPath = _path.startsWith('file:///') ? fileURLToPath(_path) : _path;
        let htmlContent = fs.readFileSync(htmlPath, "utf-8");
        htmlContent = injectImportMap(htmlContent, ResourceStorage.RuntimeProps['importmap']);
        await this._load("data:text/html;charset=utf-8," + encodeURIComponent(htmlContent), win, options);
    }

    private static async _load(
        _path: string,
        win: BrowserWindow,
        options: Electron.LoadURLOptions = {}
    ) {
        let basePath: string;
        const { app } = await import('electron');
       // console.log(app.isPackaged);

        if (app.isPackaged) {
            // packaged → resources/app.asar
            basePath = join(process.resourcesPath, "app.asar");
        } else {
            // dev → project root
            basePath = process.cwd();
        }

        const baseURL = pathToFileURL(basePath + "/").href;

        options.baseURLForDataURL ??= baseURL;
       // console.log(options.baseURLForDataURL);


        win.loadURL(_path, options);
    }
} 